[package]
name = "procmj"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
sysinfo = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
